### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by kozakl** [dhharris/pinder#1]
I can't login, I see this error

`$ /c/Python36-32/python.exe pinder.py
Traceback (most recent call last):
  File "pinder.py", line 3, in <module>
    app = PinderApp()
  File "C:\Users\Luke\Downloads\pinder-master\src\viewer.py", line 34, in __init__
    self.start_session()
  File "C:\Users\Luke\Downloads\pinder-master\src\viewer.py", line 52, in start_session
    self.prof = self.session.profile
  File "C:\Python36-32\lib\site-packages\cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Python36-32\lib\site-packages\pynder\session.py", line 22, in profile
    return Profile(self._api.profile(), self._api)
  File "C:\Python36-32\lib\site-packages\pynder\api.py", line 68, in profile
    return self._get("/profile")
  File "C:\Python36-32\lib\site-packages\pynder\api.py", line 47, in _get
    return self._request("get", url)
  File "C:\Python36-32\lib\site-packages\pynder\api.py", line 41, in _request
    raise errors.RequestError(result.status_code)
pynder.errors.RequestError: 401
`

any idea, what the happen?

**Comment by dhharris** [comment]
Hi, I believe that error is due to one of the following:

1. You have not previously authorized Tinder on Facebook
2. You have two step verification enabled.

Unfortunately, the way the app is set up currently, you cannot log in if you have two step verification.
If this didn't solve your problem, please let me know the steps you took to produce the error and I will try to debug it.

**Comment by kozakl** [comment]
Hello, unfortunately..

1. Tinder is already authorized on Facebook (I use this on normal mobile app, and works fine)
2. I have disabled two-factor authentication.

![ver](https://cloud.githubusercontent.com/assets/3715762/25236181/7e4cdd20-25e7-11e7-99e3-48ca05f563a1.PNG)

Reproduce error is really easy.

1.
log-in is fine
![login](https://cloud.githubusercontent.com/assets/3715762/25236210/94a175f4-25e7-11e7-9b92-70e804994070.PNG)

2. not responding application
![not_response](https://cloud.githubusercontent.com/assets/3715762/25236234/a2b85158-25e7-11e7-9170-9901106ea08d.PNG)

3. error in console 
![error](https://cloud.githubusercontent.com/assets/3715762/25236250/b09c9126-25e7-11e7-952f-95ca1b5045a2.PNG)


really strange, I don't know what I'm doing wrong...

**Comment by dhharris** [comment]
It looks like the program is not able to get your profile from your Tinder session. Since it made it to this line

(line 51 in viewer.py)
```python
self.session = t.Session(self.facebook_id, self.facebook_token)
```
it was able to authenticate your Facebook credentials, but for some reason the pynder library is having trouble fetching your profile. Looking at [this issue](https://github.com/charliewolf/pynder/issues/93) from the pynder library,  it seems like some users are having trouble with the newest version. Did you install the dependency using pip?

**Comment by Aimost** [comment]
Same error here.

**Comment by dhharris** [comment]
Are both of you running this on Windows?

**Comment by Aimost** [comment]
Yep, which one i should try?

**Comment by dhharris** [comment]
All of the testing I have done so far has been on a Mac, although I will have access to my Windows PC in a couple days when I'm back home. I can check it out then and see what is going on.

**Comment by kozakl** [comment]
I tried run this app on my mac, but I have same error like on Windows..
here is screenshot...
![screen shot 2017-05-11 at 11 00 55 pm](https://cloud.githubusercontent.com/assets/3715762/25971847/099156f6-369e-11e7-8851-a7ae069bfb46.png)

I tried this instruction https://gist.github.com/rtt/10403467#gistcomment-1846343
so I tried fill variable self.facebook_token to value response from facebook but first app is frozen for few seconds and after moment I get same error 401...

**Comment by dhharris** [comment]
Seems to me like an error in the pynder library

**Comment by kozakl** [comment]
I think so... Can you write witch version on pinder you use? Maybe here is problem, I have newest version...

**Comment by dhharris** [comment]
I have version 0.0.11 installed using pip and running on python 3

**Comment by kozakl** [comment]
Ok, works in 0.0.11 version of pynder.
But I have new problem, which version of geopy you use ?
Because I can't put a location, I get SSL error

![screen shot 2017-05-12 at 9 00 45 am](https://cloud.githubusercontent.com/assets/3715762/25986883/ea7addc4-36f1-11e7-9423-da5e0cd8e3d8.png)
cheers

**Comment by dhharris** [comment]
Glad that fixed the log in problem. I use version 1.11.0. Let me know if this works.

**Comment by kozakl** [comment]
Nope.. I have another error...
![screen shot 2017-05-12 at 4 27 25 pm](https://cloud.githubusercontent.com/assets/3715762/26002476/0c0381f6-3730-11e7-9e04-f5eb413fafcf.png)

probably older version of pynder doesn't work correct with current Tinder API...

**Comment by dhharris** [comment]
Okay, so I finally got around to fixing login- see 34b6ccc5fb2b7d3b8d8cebe91c2bf1f022f202cb. I think that tinder API is outdated though. I will make a new issue for that and close this one.
